#!/usr/bin/env bash
# generate-architecture.sh
# Scans the codebase and regenerates docs/architecture.md
# Run from repo root: bash scripts/generate-architecture.sh

set -euo pipefail

# grep -oP requires a UTF-8 locale (한국어 주석 포함 파일 스캔 시 C 로케일에서 실패).
# Windows + Git Bash 기본 환경에서 안전하도록 명시 고정.
export LC_ALL="${LC_ALL:-C.UTF-8}"
export LANG="${LANG:-C.UTF-8}"

cd "$(git rev-parse --show-toplevel)"

OUT="docs/architecture.md"
CHECK_MODE="${1:-}"

# ── Quick fingerprint: skip if no structural changes ────────────────────────
fingerprint() {
  {
    find src -name '*.ts' ! -name 'vite-env.d.ts' | sort
    find src-tauri/src -name '*.rs' | sort
    find src/styles -name '*.css' | sort
    grep -oP 'commands::\S+' src-tauri/src/lib.rs | sort -u
    grep -oP 'pub struct \K\w+' src-tauri/src/models.rs | sort
    grep -oP 'pub const \K\w+' src-tauri/src/models.rs | sort
  } | md5sum | cut -d' ' -f1
}

if [[ "$CHECK_MODE" == "--check" && -f "$OUT" ]]; then
  CURRENT_FP=$(fingerprint)
  # Store fingerprint as HTML comment at end of file
  STORED_FP=$(tail -1 "$OUT" | grep -oP '(?<=<!-- fp:)\w+' 2>/dev/null || echo "")
  if [[ "$CURRENT_FP" == "$STORED_FP" ]]; then
    exit 0
  fi
fi

# ── Collect file lists ──────────────────────────────────────────────────────
ts_files=$(find src -name '*.ts' ! -name 'vite-env.d.ts' | sort)
rs_files=$(find src-tauri/src -name '*.rs' | sort)
css_files=$(find src/styles -name '*.css' | sort)

ts_count=$(echo "$ts_files" | wc -l)
rs_count=$(echo "$rs_files" | wc -l)
css_count=$(echo "$css_files" | wc -l)
css_names=$(echo "$css_files" | sed 's|src/styles/||;s|\.css||' | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

# ── Extract Rust IPC commands from lib.rs ───────────────────────────────────
ipc_commands=$(grep -oP 'commands::\S+' src-tauri/src/lib.rs | sed 's/,$//' | sort -u)

# ── Extract pub struct names from models.rs ─────────────────────────────────
structs=$(grep -oP 'pub struct \K\w+' src-tauri/src/models.rs | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

# ── Extract pub const names from models.rs ──────────────────────────────────
constants=$(grep -oP 'pub const \K\w+' src-tauri/src/models.rs | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

# ── Extract Cargo dependencies ──────────────────────────────────────────────
cargo_deps=$(sed -n '/^\[dependencies\]/,/^\[/p' src-tauri/Cargo.toml \
  | grep -v '^\[' | grep -v '^$' | sed 's/ =.*//' | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

# ── Extract npm dependencies ────────────────────────────────────────────────
npm_deps=$(node -e "
  const p = require('./package.json');
  const deps = Object.entries(p.dependencies || {}).map(([k,v]) => k+' '+v);
  const dev = Object.entries(p.devDependencies || {}).map(([k,v]) => k+' '+v);
  console.log([...deps, ...dev].join(', '));
")

# ── Helper: describe TS file by first exported class/function ───────────────
describe_ts() {
  local f="$1"
  local rel="${f#src/}"
  local lines
  lines=$(wc -l < "$f")

  local desc=""
  local cls
  cls=$(grep -oP 'export class \K\w+' "$f" 2>/dev/null | head -1) || true
  if [[ -n "$cls" ]]; then
    desc="Class \`$cls\` (${lines}L)"
  else
    local fn
    fn=$(grep -oP 'export (async )?function \K\w+' "$f" 2>/dev/null | head -1) || true
    if [[ -n "$fn" ]]; then
      desc="Exports \`$fn()\` (${lines}L)"
    else
      desc="(${lines}L)"
    fi
  fi
  echo "| \`$rel\` | $desc |"
}

# ── Helper: describe RS file ────────────────────────────────────────────────
describe_rs() {
  local f="$1"
  local rel="${f#src-tauri/src/}"
  local lines
  lines=$(wc -l < "$f")

  local fns
  fns=$(grep -cP 'pub (async )?fn ' "$f" 2>/dev/null) || fns=0
  local structs_count
  structs_count=$(grep -cP 'pub struct ' "$f" 2>/dev/null) || structs_count=0

  local detail=""
  if [[ $structs_count -gt 0 && $fns -gt 0 ]]; then
    detail="${structs_count} structs, ${fns} pub fns (${lines}L)"
  elif [[ $structs_count -gt 0 ]]; then
    detail="${structs_count} structs (${lines}L)"
  elif [[ $fns -gt 0 ]]; then
    detail="${fns} pub fns (${lines}L)"
  else
    detail="(${lines}L)"
  fi
  echo "| \`$rel\` | $detail |"
}

# ── Generate ────────────────────────────────────────────────────────────────
cat > "$OUT" << 'HEADER'
# Pixel Horizon — Architecture Reference

> Auto-generated by `scripts/generate-architecture.sh`. Do not edit manually.
> Compact rules: `.claude/CLAUDE.md`

## Core Loop
`rdev::listen` (Rust) → `input::handle_input_event` → emit → `main.ts` → `CanvasManager.drawPixel()`

### Systems
- **Level Up**: XP 100 accumulation → `emit("level-up")` → notification + fireworks + palette remap
- **Skill System**: Rebirth at level 5,000 → earn SP → unlock skills (efficiency, brush, pixel precision)
- **Emoji Tracing**: Custom emoji categories overlaid on canvas via `EmojiMask`
- **Persistence**: Per-chunk `.meta` (PHB binary) + `state.json` + `horizon_stats.json` + `emoji_categories.json`

HEADER

# ── Frontend table ──────────────────────────────────────────────────────────
{
  echo "## Frontend Modules (\`src/\`) — ${ts_count} files"
  echo ""
  echo "TypeScript + Vite. ES modules, \`index.html\` as SPA entry point."
  echo ""
  echo "| Module | Info |"
  echo "|---|---|"
  while IFS= read -r f; do
    describe_ts "$f"
  done <<< "$ts_files"
  echo ""
} >> "$OUT"

# ── Backend table ───────────────────────────────────────────────────────────
{
  echo "## Backend Modules (\`src-tauri/src/\`) — ${rs_count} files"
  echo ""
  echo "Rust + Tauri 2.0."
  echo ""
  echo "| Module | Info |"
  echo "|---|---|"
  while IFS= read -r f; do
    describe_rs "$f"
  done <<< "$rs_files"
  echo ""
} >> "$OUT"

# ── CSS ─────────────────────────────────────────────────────────────────────
{
  echo "## CSS (\`src/styles/\`) — ${css_count} files"
  echo ""
  echo "Component-scoped, loaded via \`<link>\` in \`index.html\`:"
  echo "\`${css_names}\`"
  echo ""
} >> "$OUT"

# ── IPC Commands ────────────────────────────────────────────────────────────
{
  echo "## Registered IPC Commands"
  echo ""
  echo '```'
  echo "$ipc_commands"
  echo '```'
  echo ""
} >> "$OUT"

# ── Data Models ─────────────────────────────────────────────────────────────
{
  echo "## Key Data Models (\`models.rs\`)"
  echo ""
  echo "**Structs**: ${structs}"
  echo ""
  echo "**Constants**: ${constants}"
  echo ""
} >> "$OUT"

# ── Dependencies ────────────────────────────────────────────────────────────
{
  echo "## Dependencies"
  echo ""
  echo "**Cargo**: ${cargo_deps}"
  echo ""
  echo "**npm**: ${npm_deps}"
  echo ""
} >> "$OUT"

# ── Build Config ────────────────────────────────────────────────────────────
cat >> "$OUT" << 'BUILD'
## Build Configuration

- **Cargo profiles**: `[profile.dev]` (debug=0) / `[profile.release]` (thin LTO, codegen-units=1, strip symbols).
- **Linker**: Linux uses lld via `src-tauri/.cargo/config.toml`.
- **Vendored rdev**: `src-tauri/vendor/rdev` — local fork of rdev 0.5.3 fixing macOS crash. Patched via `[patch.crates-io]`.

BUILD

# ── Project tree ────────────────────────────────────────────────────────────
{
  echo "## Project Layout"
  echo '```'
  echo "pixel-horizon/"

  echo "├── .agents/rules.md"
  echo "├── .claude/CLAUDE.md"
  echo "├── .github/workflows/"
  echo "├── docs/"
  echo "├── index.html"
  echo "├── package.json"

  echo "├── src/"
  for d in $(find src -mindepth 1 -maxdepth 1 -type d | sort); do
    local_count=$(find "$d" -type f | wc -l)
    echo "│   ├── ${d#src/}/  (${local_count} files)"
  done

  echo "├── src-tauri/"
  echo "│   ├── src/  (${rs_count} files)"
  echo "│   └── vendor/rdev/"

  echo "├── tsconfig.json"
  echo "├── vite.config.ts"
  echo "└── scripts/generate-architecture.sh"
  echo '```'
} >> "$OUT"

# ── Append fingerprint for --check mode ─────────────────────────────────────
echo "<!-- fp:$(fingerprint) -->" >> "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines)"
